webapp2020/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using webapp2020.Data;
using webapp2020.Models;
using Microsoft.AspNetCore.Identity;
using System;

namespace webapp2020.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDBContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public HomeController(AppDBContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToPage("/Account/Login", new { area = "Identity" });
            }

            await BuildDataForPage(_context.Post.ToList());

            return View();
        }

        public async Task<IActionResult> FilterPosts(long? interestId, string userId)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToPage("/Account/Login", new { area = "Identity" });
            }

            List<Post> filteredPosts = _context.Post.ToList();

            if (interestId.HasValue)
            {
                filteredPosts = _context.Post.Where(t => t.InterestId == interestId).ToList();
            }

            if (userId != null)
            {
                filteredPosts = filteredPosts.Where(t => t.UserId == userId).ToList();
            }

            await BuildDataForPage(filteredPosts);

            return View("Index");
        }

        public async Task BuildDataForPage(List<Post> postlist)
        {
            ViewBag.Posts = postlist;
            ViewBag.Posts.Reverse();
            ViewBag.IsFirstPostRecommended = PutRecommendedPostAtStart(ViewBag.Posts);

            List<Interest> interests = _context.Interest.ToList();

            var usersToPosts = new List<IdentityUser>();
            var interestsToPosts = new List<Interest>();
            var likesToPost = new List<int>();
            var isLikePost = new List<bool>();

            foreach (Post post in ViewBag.Posts)
            {
                usersToPosts.Add(await _userManager.FindByIdAsync(post.UserId));
                likesToPost.Add(_context.Like.Count(g => g.PostId == post.Id));
                isLikePost.Add(_context.Like.Any(g => (g.PostId == post.Id &&
                                                       g.UserId == _userManager.GetUserId(User))));

                if (post.InterestId == 0)
                {
                    interestsToPosts.Add(null);
                }
                else
                {
                    interestsToPosts.Add(interests.Find(interest => interest.Id == post.InterestId));
                }
            }

            ViewBag.UsersToPosts = usersToPosts;
            ViewBag.Interest = interests;
            ViewBag.InterestsToPosts = interestsToPosts;
            ViewBag.likesToPost = likesToPost;
            ViewBag.isLikePost = isLikePost;
            ViewBag.Users = _context.Users.ToList();
        }

        private bool PutRecommendedPostAtStart(List<Post> posts)
        {
            // No post is recommended if there are not enough posts in total
            if (posts.Count() <= 3) {
                return false;
            }

            // Gets a list of all posts that are liked by the user
            string userId = _userManager.GetUserId(User);
            var userLikes = from l in _context.Like
                            where l.UserId == userId
                            select l;

            // All posts liked by the user
            List<Post> postsLikedByUser = (from p in posts
                                           join ul in userLikes on p.Id equals ul.PostId
                                           select p).ToList();

            // Find all liked interests by the user
            Dictionary<long, int> likedInterests = new Dictionary<long, int>();
            foreach (var interest in _context.Interest) 
            {
                likedInterests.Add(interest.Id, 0);
            }
            foreach (var likedPost in postsLikedByUser)
            {
                if (likedPost.InterestId != 0)
                {
                    likedInterests[likedPost.InterestId] += 1;
                }
            }

            // Algorithm constants for evaluation
            double OLD_POST_EVALUATION_PENALTY = 0.05;
            double LIKED_BY_USER_BONUS = 0.4;
            double INTEREST_BONUS = 0.15;

            double maxEvaluation = Double.MinValue;
            int bestPostIndex = -1;

            // Evaluate each posts based on user likes and his most liked interests and post time
            for (int postIndex = 0; postIndex < posts.Count(); postIndex++)
            {
                double currentEvaluation = 0;

                Post post = posts[postIndex];
                bool isPostLikedByUser = postsLikedByUser.Any(p => p.UserId == userId);

                // Apply penalty for old posts
                currentEvaluation -= postIndex * OLD_POST_EVALUATION_PENALTY;

                // Add bonus if post is liked by user
                if (isPostLikedByUser) {
                    currentEvaluation += LIKED_BY_USER_BONUS;
                }

                // Add bonus if same post interest was liked many times by the user
                if (post.InterestId != 0) {
                    currentEvaluation += likedInterests[post.InterestId] * INTEREST_BONUS;
                }

                // If we find better evaluation, then we replace the best one with it
                if (currentEvaluation > maxEvaluation)
                {
                    maxEvaluation = currentEvaluation;
                    bestPostIndex = postIndex;
                }
            }

            // Put best evaluated post at the start of the posts list
            var temp = posts[0];
            posts[0] = posts[bestPostIndex];
            posts[bestPostIndex] = temp;

            return true;
        }

        public IActionResult FavoritePlaces()
        {
            return View();
        }

        public IActionResult OurStory()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

webapp2020/Controllers/PostsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using webapp2020.Data;
using webapp2020.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace webapp2020.Controllers
{
    public class PostsController : Controller
    {
        private readonly AppDBContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public PostsController(AppDBContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Posts
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Post.ToListAsync());
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Post
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Content,InterestId")] Post post)
        {
            if (ModelState.IsValid)
            {
                post.UserId = _userManager.GetUserId(User);
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return View(post);
        }

        // GET: Posts/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Post.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> EditPost([Bind("Id,Content,UserId, InterestId")] Post post)
        {
            try
            {
                _context.Update(post);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PostExists(post.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Index", "Home");
        }


        // POST: Posts/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(long id)
        {
            string userId = _userManager.GetUserId(User);

            var post = await _context.Post.FindAsync(id);

            if (userId == post.UserId || User.IsInRole("Admin"))
            {
                _context.Post.Remove(post);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Index", "Home");
        }

        // GET: Posts/DeleteConfirmed/5
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var post = await _context.Post.FindAsync(id);
            _context.Post.Remove(post);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(long id)
        {
            return _context.Post.Any(e => e.Id == id);
        }
    }
}

webapp2020/Views/Home/FavoritePlaces.cshtml
@{
    ViewData["Title"] = "Favorite places to visit";
}
<head>
    <link rel="stylesheet" href="~/css/map.css" />
</head>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/map.js"></script>
<script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?branch=release&callback=loadMap' async defer></script>


<div class="mapPageWrapper">
    <h1 style="padding-bottom: 1rem">@ViewData["Title"]</h1>
    <div style="padding: 2rem;"></div>

    <h4>Here are our favorite places to visit in Israel</h4>

    <div style="padding: 2rem;"></div>

    <div id="map"></div>
</div>

webapp2020/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager
@{
    ViewData["Title"] = "Home Page";

    string[] badgeStyles = { "primary", "secondary", "success", "danger", "warning", "info", "dark" };
    Dictionary<long, String> interestToBadge = new Dictionary<long, String>();
    for (int interestIndex = 0; interestIndex < ViewBag.Interest.Count; interestIndex++)
    {
        var id = ViewBag.Interest[interestIndex].Id;
        interestToBadge.Add(id, badgeStyles[id % badgeStyles.Length]);
    }

    var user = await UserManager.GetUserAsync(User);
    var userId = user?.Id;
}

<head>
    <link rel="stylesheet" href="~/css/post.css" />
</head>
<script src="~/js/post.js"></script>

<div class="text-center">
    <div class="row">
        <div class="col-md-3">
            <p class="lead">
                NEWS
            </p>
            <div id="News"></div>
        </div>
        <div class="col-md-6">
            <form id="search" method="get" enctype="multipart/form-data" asp-controller="Home" asp-action="FilterPosts" class="row">
                <select id="searchSelect" class="custom-select col-lg-4 col-md-4" name="interestId">
                    <option value="" selected>Interest</option>
                    @for (int i = 0; i < ViewBag.Interest.Count; i++)
                    {
                        <option value="@ViewBag.Interest[i].Id">@ViewBag.Interest[i].Name</option>
                    }
                </select>
                <select id="searchSelect" class="custom-select col-lg-4 col-md-4" name="userId">
                    <option value="" selected>Member</option>
                    @for (int i = 0; i < ViewBag.Users.Count; i++)
                    {
                        <option value="@ViewBag.Users[i].Id">@ViewBag.Users[i].UserName</option>
                    }
                </select>
                <div id="searchButton">
                    <button class="btn btn-light btn-sm"><i class="glyphicon glyphicon-search"></i></button>
                    <button type="button" class="btn btn-light btn-sm" onclick="window.location.href = '/Home'">X</button>
                </div>
            </form>
            <div id="postCard" class="card">
                <div style="display: flex; flex-direction:row; justify-content:space-between">
                    <form onsubmit="return validatePostForm()" name="postForm" method="post" enctype="multipart/form-data" asp-controller="Posts" asp-action="Create" style="width:100%">
                        <input id="postInput" name="content" placeholder="What's on your mind?" />
                        <button class="btn btn-light">Post</button>
                        @for (int interestIndex = 0; interestIndex < ViewBag.Interest.Count; interestIndex++)
                        {
                            <a class="badge badge-pill badge-@interestToBadge[ViewBag.Interest[interestIndex].Id]"
                               id="InterestId"
                               style="color: azure"
                               onclick="setInterestId('@ViewBag.Interest[interestIndex].Id')"
                               name="InterestId" href="#">
                                @ViewBag.Interest[interestIndex].Name
                            </a>
                        }
                        <input type="hidden" name="InterestId" id="InterestHiddenInput" value="0" />
                    </form>
                </div>
            </div>
            @for (int postIndex = 0; postIndex < ViewBag.Posts.Count; postIndex++)
            {
                <input id="postId" type="hidden" value="@ViewBag.Posts[postIndex].Id" />
                <input id="postIndex" type="hidden" value="@postIndex" />
                <div id="postCard" class="card @(ViewBag.IsFirstPostRecommended && postIndex == 0 ? "recommended-post" : "")">
                    <section>
                        <div class="postdetails">
                            <div class="username">@ViewBag.UsersToPosts[postIndex]?.UserName</div>
                            <div class="rightSidePostDetails">
                                @if (ViewBag.InterestsToPosts[postIndex] != null)
                                {
                                    <a style="color: azure" class="interestTag badge badge-pill badge-@interestToBadge[ViewBag.InterestsToPosts[postIndex].Id]">
                                        @ViewBag?.InterestsToPosts[postIndex]?.Name
                                    </a>
                                }

                                @if (User.IsInRole("Admin") || userId == ViewBag.Posts[postIndex].UserId)
                                {
                                    <button data-toggle="modal" data-target="#editpost"
                                            onclick="fillEditPostDetails('@ViewBag.Posts[postIndex].Id', '@ViewBag.Posts[postIndex].Content', '@ViewBag.Posts[postIndex].UserId')"
                                            class="btn btn-xs btn-light">
                                        Edit
                                    </button>
                                    <div class="closeButtonPart">
                                        <form method="post" enctype="multipart/form-data" asp-controller="Posts" asp-action="Delete">
                                            <button class="btn btn-xs btn-danger">X</button>
                                            <input name="Id" hidden value="@ViewBag.Posts[postIndex].Id" />
                                        </form>
                                    </div>
                                }
                            </div>
                        </div>

                        <p class="card-text" style="text-align: left;">@ViewBag.Posts[postIndex].Content</p>
                    </section>
                    <div class="dropdown-divider"></div>
                    <div class="actionButtons">
                        <div class="likeButtonPart">
                            <div class="numOfLikes" id="numOfLikes-@postIndex" value="0">
                                @ViewBag.likesToPost[postIndex]
                            </div>
                            <button id="likeButton-@postIndex"
                                    onclick="isLikedThePost('@ViewBag.Posts[postIndex].Id', @postIndex)"
                                    class="@(ViewBag.isLikePost[postIndex] ? "btn btn-primary" : "btn btn-light")">
                                Like
                            </button>
                        </div>
                        <a data-size="large" class="twitter-share-button"
                            href="https://twitter.com/intent/tweet?text=Post%20I%20Made%20at%20Stark:@(" "+ ViewBag.Posts[postIndex].Content + " ")">
                            Tweet
                        </a>
                    </div>
                </div>
            }
        </div>
        <div class="col-md-3">
            <a class="twitter-timeline" data-height="1000" href="https://twitter.com/TwitterDev?ref_src=twsrc%5Etfw">Tweets by TwitterDev</a>
            <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
    </div>
</div>

<div class="modal fade" id="editpost" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog modalDialogStyle">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Post</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" enctype="multipart/form-data" asp-controller="Posts" asp-action="EditPost">
                <div class="modal-body modalBodyStyle">
                    <input type="hidden" name="Id" id="editPostId" />
                    <input type="hidden" name="UserId" id="editUserId" />

                    <h4>Content:</h4>
                    <input class="form-control" id="editContent" type="text" name="Content" required><br />

                    <h4>Interest:</h4>
                    <select class="custom-select col-lg-4 col-md-4" name="InterestId">
                        <option value="0">No interest</option>
                        @for (int i = 0; i < ViewBag.Interest.Count; i++)
                        {
                            <option value="@ViewBag.Interest[i].Id">@ViewBag.Interest[i].Name</option>
                        }
                    </select>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-light">Save</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">X</button>
                </div>
            </form>
        </div>
    </div>
</div>

webapp2020/Views/Home/OurStory.cshtml
@{
    ViewData["Title"] = "Our Story";
}

<div style="display:flex; justify-content:center; flex-direction: column; padding: 3rem; align-items: center; text-align:center">
    <h1 style="padding-bottom: 1rem">@ViewData["Title"]</h1>

    <h4 style="padding-bottom: 2rem">We are a passionate group of students, looking to bring people with similar interests together across the entire world</h4>

    <h4 style="padding-bottom: 2rem">Social medias connect billions of people on a daily basis, and allow them to share their experiences and ideas</h4>

    <h4>Learn more about the benefits of social medias</h4>

    <div style="width: 80%; height: 30rem; padding-top: 2rem;">
        <video controls style="object-fit: cover; height:auto; max-width:100%; box-shadow: 1px 1px 3px -1px;">
            <source src="~/social_medias.mp4" type="video/mp4">
        </video>
    </div>
</div>