webapp2020/Controllers/InterestsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using webapp2020.Data;
using webapp2020.Models;
using Microsoft.AspNetCore.Authorization;

namespace webapp2020.Controllers
{
    public class InterestsController : Controller
    {
        private readonly AppDBContext _context;

        public InterestsController(AppDBContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Interest.ToListAsync());
        }

        // GET: Interests/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var interest = await _context.Interest
                .FirstOrDefaultAsync(m => m.Id == id);
            if (interest == null)
            {
                return NotFound();
            }

            return View(interest);
        }

        // GET: Interests/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Interests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Interest interest)
        {
            if (ModelState.IsValid)
            {
                _context.Add(interest);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(interest);
        }

        // GET: Interests/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var interest = await _context.Interest.FindAsync(id);
            if (interest == null)
            {
                return NotFound();
            }
            return View(interest);
        }

        // POST: Interests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Interest interest)
        {
            if (id != interest.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(interest);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InterestExists(interest.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(interest);
        }

        // GET: Interests/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var interest = await _context.Interest
                .FirstOrDefaultAsync(m => m.Id == id);
            if (interest == null)
            {
                return NotFound();
            }

            return View(interest);
        }

        // POST: Interests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var interest = await _context.Interest.FindAsync(id);
            _context.Interest.Remove(interest);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InterestExists(int id)
        {
            return _context.Interest.Any(e => e.Id == id);
        }

        [HttpGet]
        public ActionResult GetInterests(string term)
        {
            return Json(_context.Interest.Where
                (c => c.Name.StartsWith(term)).Select(a => new { label = a.Name }));
        }
    }
}

webapp2020/Controllers/LocationsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using webapp2020.Data;
using webapp2020.Models;
using Microsoft.AspNetCore.Authorization;
using System.Collections.Generic;

namespace webapp2020.Controllers
{
    public class LocationsController : Controller
    {
        private readonly AppDBContext _context;

        public LocationsController(AppDBContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin")]
        // GET: Locations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Location.ToListAsync());
        }

        [HttpGet]
        public async Task<List<Location>> All()
        {
            return await _context.Location.ToListAsync();
        }

        // GET: Locations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var location = await _context.Location
                .FirstOrDefaultAsync(m => m.Id == id);
            if (location == null)
            {
                return NotFound();
            }

            return View(location);
        }

        // GET: Locations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Latitude,Longitude")] Location location)
        {
            if (ModelState.IsValid)
            {
                _context.Add(location);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(location);
        }

        // GET: Locations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var location = await _context.Location.FindAsync(id);
            if (location == null)
            {
                return NotFound();
            }
            return View(location);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Latitude,Longitude")] Location location)
        {
            if (id != location.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(location);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocationExists(location.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(location);
        }

        // GET: Locations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var location = await _context.Location
                .FirstOrDefaultAsync(m => m.Id == id);
            if (location == null)
            {
                return NotFound();
            }

            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var location = await _context.Location.FindAsync(id);
            _context.Location.Remove(location);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LocationExists(int id)
        {
            return _context.Location.Any(e => e.Id == id);
        }
    }
}

webapp2020/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using webapp2020.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;


namespace webapp2020.Controllers
{
    public class StatisticsController : Controller
    {
        private const int MAX_USERS_TO_POSTS_COUNT = 5;
        private readonly AppDBContext _context;

        public StatisticsController(AppDBContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View();
        }
        

        [HttpGet]
        public IEnumerable<UserToPostCount> GetTopUserToPostCounts()
        {
            var UsersToPosts = from u in _context.Users
                               join p in _context.Post on u.Id equals p.UserId
                               select new { Username = u.UserName, PostId = p.Id };

            var UsersToPostCounts = from userToPost in UsersToPosts
                                    group userToPost by userToPost.Username into k
                                    select new UserToPostCount() { NumberOfPosts = k.Count(), Username = k.Key };

            return (from userToPostCount in UsersToPostCounts
                    orderby userToPostCount.NumberOfPosts descending
                    select userToPostCount).Take(MAX_USERS_TO_POSTS_COUNT)
                    .ToList();
        }

        [HttpGet]
        public IEnumerable<InterestToLikeCount> GetInterestsToLikesCounts() 
        {
            var AllPostInterestsWithLikes = from l in _context.Like
                               join p in _context.Post on l.PostId equals p.Id
                               select new { Id = p.InterestId };

            var InterestsIdsToLikeCounts = from InterestWithLike in AllPostInterestsWithLikes
                                           group InterestWithLike by InterestWithLike.Id into t
                                           select new { NumberOfInterestLikes = t.Count(), Id = t.Key };

            List<InterestToLikeCount> InterestToLikes = new List<InterestToLikeCount>();
            foreach (var interestIdToLikeCount in InterestsIdsToLikeCounts)
            {
                InterestToLikes.Add(new InterestToLikeCount()
                {
                    InterestName = GetInterestNameById(_context, interestIdToLikeCount.Id),
                    LikeCount = interestIdToLikeCount.NumberOfInterestLikes
                });
            }

            return InterestToLikes;
        }

        private string GetInterestNameById(AppDBContext context, long InterestId)
        {
            if (InterestId == 0) 
            {
                return "No interest";
            }

            return (from i in _context.Interest
                    where i.Id == InterestId
                    select i.Name).FirstOrDefault();
        }

        public class UserToPostCount
        {
            public String Username { get; set; }
            public int NumberOfPosts { get; set; }
        }


        public class InterestToLikeCount 
        {
            public String InterestName { get; set; }
            public int LikeCount { get; set; }
        }
    }
}

webapp2020/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Stark</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color: #f0f2f5">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <canvas id="starkCanvas" width="130" height="70"></canvas>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>

                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Interests" asp-action="Index">Interests</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Locations" asp-action="Index">Locations</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Statistics" asp-action="Index">Statistics</a>
                                </li>
                            }

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="FavoritePlaces">Favorite places</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="OurStory">Our story</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" id="footerMain">
            &copy; 2020 - Stark
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>